### ISSUE TITLE
Feature Req Minimal Package

### ISSUE THREAD

**Issue by lavenderdotpet** [manglemix/Trokara#5]
A version that would have only what is required for fps and tps and nothing else

**Comment by Axsajim** [comment]
You mean, just simplifying the Whole Project into one addon with two nodes and just adds a "FPS - Player.tscn" and "TPS - Player.tscn" to you project in the Unity way?

I mean, the project is literally **A modular package for developing terrestrial characters**, so the whole project state right now is about making _"A version with only what is required for fps and tps"_.

I understand if you consider this is too much technical for someone who doesn't wants to learn terrestrial kinematics physics and their systems. So, if you could confirm me that what you are looking for is a **This, but easier to use, understand and manage** I would try helping you out 👍

**Comment by manglemix** [comment]
I just made a commit sorting scripts into 2D and 3D. All the scripts in the 3D folder should be essential to a FPS or TPS

**Comment by lavenderdotpet** [comment]
oh cool ill try it out
