### ISSUE TITLE
Character doesn't correctly rotate with rotating flatforms

### ISSUE THREAD

**Issue by Janders1800** [manglemix/Trokara#9]
If 'use_true_movement' in 'face_movement.gd' is set to true the character will always face the direction of the platform rotation, since that's the vector movement.

And if is set to false it doesn't rotate with the platform at all.

**Comment by manglemix** [comment]
Thank you for your script, I appreciate that you took the effort to fix it. But I will be reworking this code to be much better since the coding style I used here is actually not very good

**Comment by manglemix** [comment]
And when I say reworking this code I'm actually referring to the entire repo, not your script specifically
